config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations', :confirmations => 'confirmations', :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    patch "/confirm" => "confirmations#confirm"
  end
  resources :users, :only => [:show]

  resources :events, :only => [:show, :new, :create, :destroy, :edit, :update, :index] do

    collection do #events/
      post 'filtered'
      post 'search'
    end

    member do #event/:id/ with :id passed in params[:id]
    end

    post 'follow', to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  roles = [:default, :private, :public, :owner]
  resources :comments, :only => [:create, :destroy, :show] do
    roles.each do |role|
      patch "set_#{role}", on: :member, as: "set_#{role}"
    end
  end

  get 'comments#paginate', controller: "comments", action: "paginate"

  

  
  resources :tags, :only => [:show, :create, :destroy]

  get 'schedule/list'

  get 'schedule/calendar'
  get 'schedule/calendar', as: 'schedule'
  get '/schedule', to: redirect('schedule/calendar') 

  match '/feed',       controller: 'static_pages', action: 'feed',        via: [:get, :post], as: 'feed'
  match '/saved',      controller: 'static_pages', action: 'saved',       via: [:get, :post], as: 'saved'
  match '/activities', controller: 'static_pages', action: 'activities',  via: [:get, :post], as: 'activities'
  get '/activities/event/:id', to: 'static_pages#activity_list'
  
  root 'static_pages#feed'

  get '/access_error', to: 'errors#access'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get "*any", via: :all, to: "errors#not_found"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_events, only: [:feed, :saved, :activities]

  def saved
  	@events = @events.where(id: (current_user.followees(Event) | current_user.events)).deef

    respond_to do |format|
      format.html { 
          render "static_pages/feed" 
      }
      format.js { 
          render "static_pages/_feed.js.erb", 
          locals: 
          {
              item_partial: "events/event",
              items: @events
          } 
      }
    end

  end

  def feed
    @events = @events.starts_after(DateTime.now.to_date).deef

    respond_to do |format|
      format.html { 
          render "static_pages/feed"
      }
      format.js { 
          render "static_pages/_feed.js.erb",
          locals: 
          {
              item_partial: "events/event",
              items: @events
          }
      }
    end
  end

  def activities
    @events = @events.where(id: (current_user.followees(Event) | current_user.events)).by_newest_activity

    respond_to do |format|
      format.html { 
          render "static_pages/activities" 
      }
      format.js { 
          render "static_pages/_feed.js.erb",  
          locals: 
          {
              item_partial: "static_pages/activity_toggle",
              items: @events
          }
      }
    end

  end

  def activity_list
    event = Event.find(params[:id])
    activities = PublicActivity::Activity.where(owner: event ).order("created_at DESC")

    respond_to do |format|
      format.html { 
          render "static_pages/activity_list",
          locals:
          {
              event: event,
              activities: activities
          } 
      }
      format.js { 
          render partial: "static_pages/activity_list", 
          locals: 
          {
              event: event,
              activities: activities
          }
      }
    end

  end

  private

    def set_events
      @events = Event.where(nil)
      params[:search_return] = nil

      if params.include?(:search)
        @events = @events.search(params[:search])
        params[:search_return] = params[:search]
      end

      if params.include?(:page)
        @events = EventsHelper.pagi(@events, page: params[:page])
      else
        @events = EventsHelper.pagi(@events, page: 1)
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_activity_list.html.erb
<%= render partial: 'events/event', 
	locals: 
	{ 
		event: event,
		svg_thn: 'svg/icons/letterx.svg',
		link: event,
		data: { detail: true } 
	} 
%>

<%= 
content_tag :div,
class: "activity-list col h4", 
data: {} do
%>
  <%= render_activities(activities, layout: :activity) %>
<% end %>

app/views/static_pages/_activity_list.js.erb
var $deselected = $(".activity-feed > [data-drop], [data-scroll-link]");
var $selected = $("<%= j render partial: 'static_pages/activity_list.html.erb', locals: {event: event, activities: activities} %>");

$deselected.addClass("hidden");
$(".activity-feed").prepend($selected);
window.location.hash = '<%= "detail" %>'; /* event.id.to_s */

$(document).trigger("scroll:stop");
$(".svg-link").on("click",
	function()
	{
		$(".svg-link").off("click");
		$selected.detach();
		$deselected.removeClass("hidden");
		$(document).trigger("scroll:start");
		window.location.hash = '';
	}
);

app/views/static_pages/_activity_toggle.html.erb
<%= render partial: 'events/event', 
	locals: 
	{ 
		event: event,
		svg_thn: 'svg/test/arrow_3.svg',
		link: false,
		classes: "drop-event",
		data: drop_snd(event.id).merge({id: event.id})
	} 
%>
<%= 
content_tag :div,
class: "activity-list col h4", 
data: drop_rcv(event.id) do
%>
  	<%= render partial: 'activities/list', 
  	locals: {activities: ActivitiesHelper.pagi(event.activities) } %>
<% end %>

app/views/static_pages/_feed.js.erb
/*
	if you wanted to break this into two:
	1. separate scroll partial from js
	2. reload entire scroll partial for search
	3. js checks the on/off parameter set by loading the partial
*/
<% if params[:search_return] %>
	/* THIS COULD BE IN SEARCH/RETURN OR REPLACE_PARTIAL OR SOMETHING */
	$('[data-scroll-content]').html("<%= j render(partial: item_partial, collection: items, format: 'html', as: items.take.class.name.downcase.to_sym) %>");
	$(document).trigger("callbacks:reset");
	window.location.hash = "<%= 'search?' + params[:search_return] %>";
<% else %>
	$('[data-scroll-content]').append("<%= j render(partial: item_partial, collection: items, format: 'html', as: items.take.class.name.downcase.to_sym) %>");
<% end %>

$('[data-scroll-link]').replaceWith("<%= j scroll_link(items) %>");

app/views/static_pages/activities.html.erb
<%= form_tag url_for(controller: 'static_pages', action: 'activities'), remote: true, 
	class: 'activity search row h2' do %>
  <%= hidden_field_tag :items, @events.unscope(:limit).pluck(:id).join(',') %>
  <%= text_field_tag :search, params[:search], placeholder: "search" %>
  <%= submit_tag '>>' %>
<% end %>

<div class="activity-feed feed col" data-scroll-content="1" data-search-target="1">
		<%= render partial: 'static_pages/activity_toggle',
		collection: @events, as: :event %>
</div>

<%= render partial: "shared/scroll", locals: {items: @events} %>

app/views/static_pages/activity_feed.html.erb
<%= form_tag url_for(controller: 'events', action: 'search', target: 'activities'), remote: true, 
	class: 'activity search row h2' do %>
  <%= hidden_field_tag :items, @events.pluck(:id).join(',') %>
  <%= text_field_tag :search, params[:search], 
  placeholder: "render partial: 'events/activities', collection: @events, as: :event" %>
  <%= submit_tag '>>' %>
<% end %>

<div class="activity-feed feed col" data-search-target="1" data-scroll-content="1">

		<% @events.each do |event| %>
				<%= render partial: 'events/event', 
					locals: 
					{ 
						event: event,
						svg_thn: 'svg/test/arrow_3.svg',
						link: false,
						classes: "drop-event",
						data: drop_snd(event.id).merge({id: event.id})
					} 
				%>
				<%= content_tag :div,
					class: "activity-list col h4", 
					data: drop_rcv(event.id) do %>

				  	<%= render_activities(
					  	event.activities.order(:role, :created_at).page(1).per(10), 
					  	layout: :activity 	)%>

				  	<% if (event.activities.count > 10) %>
				  		<%= link_to "#{event.activities.count - 10} more...", 
				  			remote: true, 
				  			controller: "static_pages", 
				  			action: "activity_list", 
				  			id: event.id %>
					<% end %>
				<% end %>
		<% end %>
</div>

<%= render partial: "shared/scroll", locals: {items: @events} %>

app/views/static_pages/feed.html.erb
<div id="bar-b" class="nav-bar row h2">
	<%= link_to 'explore', feed_path, class: 'item' %> | 
	<%= link_to 'my schedule', saved_path, class: 'item' %>
</div>

<%= render 'events/feed' %>

<%= render partial: "shared/scroll", locals: {items: @events} %>