config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations', :confirmations => 'confirmations', :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    patch "/confirm" => "confirmations#confirm"
  end
  resources :users, :only => [:show]

  resources :events, :only => [:show, :new, :create, :destroy, :edit, :update, :index] do

    collection do #events/
      post 'filtered'
      post 'search'
    end

    member do #event/:id/ with :id passed in params[:id]
    end

    post 'follow', to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  roles = [:default, :private, :public, :owner]
  resources :comments, :only => [:create, :destroy, :show] do
    roles.each do |role|
      patch "set_#{role}", on: :member, as: "set_#{role}"
    end
  end

  get 'comments#paginate', controller: "comments", action: "paginate"

  

  
  resources :tags, :only => [:show, :create, :destroy]

  get 'schedule/list'

  get 'schedule/calendar'
  get 'schedule/calendar', as: 'schedule'
  get '/schedule', to: redirect('schedule/calendar') 

  match '/feed',       controller: 'static_pages', action: 'feed',        via: [:get, :post], as: 'feed'
  match '/saved',      controller: 'static_pages', action: 'saved',       via: [:get, :post], as: 'saved'
  match '/activities', controller: 'static_pages', action: 'activities',  via: [:get, :post], as: 'activities'
  get '/activities/event/:id', to: 'static_pages#activity_list'
  
  root 'static_pages#feed'

  get '/access_error', to: 'errors#access'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get "*any", via: :all, to: "errors#not_found"

end

app/views/layouts/_activity.html.erb
<%= content_tag :div, class: ["item", "row", "h4"],
	data: { fresh: "#{fresh?(activity)}", role: activity.parameters[:role] } do %>
	<%= date_style(activity.created_at) %> -
	<span class="title"> <%= activity.trackable.title %> </span>
<% end %>

app/views/layouts/_paginate.html.erb
<%= content_tag :div, class: "h5",
	data: {
		pagi_link: target,
		current: items.current_page, 
		total: items.total_pages, 
		first: "#{items.current_page == 1}",
		last: "#{items.current_page == items.total_pages}"
		} do %>
	<%= paginate items, remote: true, params: params %>

<% end %>

app/views/layouts/_scroll.html.erb
<% content_for :footer do %>
	<%= javascript_include_tag "infinite_scroll" %>
<% end %>


<%= content_tag :div, data: { 
	scroll_link: (items.current_page < items.total_pages) ? "1" : "0",
	current: items.current_page, 
	total: items.total_pages } do %>
	<%= link_to('...', url_for(page: items.current_page + 1)) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 
  	(controller.controller_name if javascript_exists?(controller.controller_name)),
  	("#{controller.controller_name}-#{controller.action_name}" if javascript_exists?("#{controller.controller_name}-#{controller.action_name}")),
  	'data-turbolinks-track' => true
  %>
  <%= csrf_meta_tags %>
</head>

<body class="know"
	data-controller=
	<%= "#{controller.controller_name}" %>
	data-action=
	<%= "#{controller.action_name}" %>
	data-url= 
	<%= "#{request.fullpath}" %>
> 

<div id="bar-t" class="nav-bar row">
<% if user_signed_in? %>
	<div class="br"> </div>
	<a 	href="<%= new_event_path %>"
		class="item svg-link" >
		<%= inline_svg 'svg/icons/plus.svg', 
			class: "svg-plus" 
		%>
	</a>
	<a 	href="<%= root_path %>"
		class="item svg-link" >
		<%= inline_svg 'svg/icons/home.svg',
			class: "svg-home" 
		%>
	</a>
	<a 	href="<%= schedule_path %>"
		class="item svg-link" >
		<%= inline_svg 'svg/icons/calendar.svg',
			class: "svg-calendar"
		%>
	</a>
	<a 	href="<%= activities_path %>"
		class="item svg-link" >
		<%= inline_svg 'svg/icons/alert.svg',
			class: "svg-alert"
		%>
	</a>
	<a 	href="<%= user_path(current_user.id) %>"
		class="item svg-link" >
		<%= inline_svg 'svg/icons/user.svg',
			class: "svg-user"
		%>
	</a>
	<%= content_tag :a, 
	href: destroy_user_session_path, 
	data: { method: :delete },  
	class: "item svg-link", 
	rel: "nofollow" do %>
		<%= inline_svg 'svg/icons/logout.svg',
			class: "svg-logout"
		%>
	<% end %>
<% else %>
<% end %>
</div>




<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="know-page">
	<div class="vmn"> </div>
	<%= yield %>
</div>

</body>



<footer> <%= content_for :footer %> </footer>
</html>